export const glossary = {
  bullseye: {
    term: "Bull's Eye",
    definition:
      "An H&Z standardized framework and logic that facilitates the mutual discussion between sourcing teams and business partners (cost center owners) regarding value creation, resilience and sustainability potentials along different optimization areas (Demand, Specification, Sourcing, and Execution).",
  },
  lever: {
    term: "Lever",
    definition:
      "An action that leads to the successful achievement of a potential. These actions can be classified into three main focus areas depending on the desired potential or impact (a lever can impact one or multiple focus areas simultaneously):",
    sub: [
      {
        term: "Value Creation levers",
        definition: "Lead to decreases in costs.",
      },
      {
        term: "Sustainability levers",
        definition:
          "Lead to improvements in environmental, social or governance performance and supports ESRS reporting.",
      },
      {
        term: "Resilience levers",
        definition: "Improve the supply performance.",
      },
    ],
  },
  optimization_area: {
    term: "Optimization areas",
    definition: "Levers are grouped into four optimization areas:",
    sub: [
      {
        term: "Demand",
        definition:
          "Improves planning, ordering, and handling quantities of products and services",
      },
      {
        term: "Specification",
        definition: "Challenges product design and its functionalities",
      },
      {
        term: "Sourcing",
        definition:
          "Assesses the strategies of identifying and procuring products and services",
      },
      {
        term: "Execution",
        definition: "Focuses on process design and implementation",
      },
    ],
  },
  clusters: {
    term: "Clusters",
    definition:
      "In each optimization area, levers are further classified in 8 MECE (mutually exclusive and collectively exhaustive) clusters:",
    sub: [
      {
        term: "Specification",
        sub: ["Cost Value Engineering (CVE)", "Innovation"],
      },
      {
        term: "Sourcing",
        sub: ["Value Chain and Sourcing (VC and Sourcing)", "Negotiations"],
      },
      {
        term: "Demand",
        sub: ["Demand Management", "Forecasting and Planning"],
      },
      {
        term: "Execution",
        sub: [
          "Financeand Supply Chain Processes (F&SC Processes)",
          "Environmental, Social, Governance",
        ],
      },
    ],
  },
  mta: {
    term: "Measures / Tools / Activities",
    definition:
      "Specific sub-actions, methods and/or processes to execute a lever successfully. Multiple measures/tools/activities can be carried out or implemented to achieve the potential of a lever.",
  },
  ip: {
    term: "Impact / Potential",
    definition: "The expected outcome of implementing a lever successfully.",
  },
  approach: {
    term: "Approach",
    definition: "High-level process description to implement lever.",
  },
  implementation_timeline: {
    term: "Implementation timeline",
    definition:
      "Expected period to fully implement a lever as described in the approach. The following scales are assumed throughout this tool: Short-term: <6 months, Mid-term: 6-12 months, Long-term: >12 months",
    sub: [
      { term: "Short-term", definition: "<6 months" },
      { term: "Mid-term", definition: "6-12 months" },
      { term: "Long-term", definition: ">12 months" },
    ],
  },
  kpi: {
    term: "KPI",
    definition: "A metric used to assess the effectiveness of actions taken.",
  },
  vc_kpi: {
    term: "Value Creation KPI",
    sub: [
      {
        term: "PPC – Purchasing Price Change",
        definition:
          "Tracks the change in purchase prices over time. It measures how effectively procurement is negotiating and securing better pricing from suppliers (lower price for same goods/services).",
      },
      {
        term: "MCP – Material Cost Productivity",
        definition:
          "Measures how efficiently the procurement team is reducing material costs relative to the company's output or sales growth (material efficiency).",
      },
      {
        term: "VAM – Value Added Measures",
        definition:
          "Evaluates the additional value generated by procurement activities beyond basic cost savings (additional service for same price). It could include innovation, supplier development, risk mitigation, or sustainability achievements.",
      },
      {
        term: "CTG – Contribution to Growth",
        definition:
          "Measures procurement's direct impact on company revenue growth. It reflects how sourcing strategies support business expansion through cost efficiency, faster time-to-market, or enabling new product launches.",
      },
      {
        term: "ANR – Advanced Negotiation Results",
        definition:
          "Measures the outcomes of strategic negotiations that go beyond basic cost reductions, including factors like contract flexibility, improved payment terms, service-level agreements (SLAs), or long-term partnership benefits.",
      },
    ],
  },
  sustainability_kpi: {
    term: "Sustainability KPIs",
    sub: [
      {
        term: "CO2e",
        definition:
          "Measures progress in reducing direct and indirect carbon dioxide equivalent emissions.",
      },
      {
        term: "Circularity Rating",
        definition:
          "Measures repairability, recyclability, circular product design, and percentage of raw materials and components made from recycled or repurposed materials.",
      },
      {
        term: "CoC adherence",
        definition:
          "Ratio of suppliers with an accepted and complying with supplier Code of Conduct.",
      },
      {
        term: "Supplier risk score",
        definition:
          "Rating of a supplier's risk assessment based on adherence to environmental, social and governance targets",
      },
    ],
  },
  resilience_kpi: {
    term: "Resilience KPIs",
    sub: [
      {
        term: "OTIF – On-Time-in-Full",
        definition:
          "How often a company delivers the correct order quantities on the agreed-upon delivery date, thereby meeting customer demand.",
      },
      {
        term: "Avg. Lead Time",
        definition:
          "The average period between when an order is placed and when that order is delivered.",
      },
      {
        term: "Safety Stock",
        definition:
          "The extra quantity of a product which is stored to prevent an out-of-stock situation.",
      },
      {
        term: "Percentage of Single-Source Spend",
        definition:
          "Ratio of spend that is covered by a single supplier (across all commodities).",
      },
    ],
  },
};
